services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  gcs:
    image: fsouza/fake-gcs-server:latest
    ports:
      - 4443:4443
    volumes:
      - ./src/main/resources/gcp:/data
    command: -scheme http